#!/usr/bin/julia
module jcompWrapper

using PackageCompiler, Comonicon, Dates, Pkg, ShareAdd
const DEFAULT_DIR = "$(ENV["HOME"])/.julia/sysimages"
const NOW = Dates.now()
const JCOMP_TMP = "/tmp/jcomp"
"""

jcomp: configure and compile julia sysimages for you.

# Args

- `env`: julia enviroment that the sysimage is being created for (will use the Pkg.activate default if not supplied).

# Options

- `--trace-file=<path>`: precompile_statements_file for sysimage creation.
- `--excluded=<list>`: comma seperated list of packages to exclude from sysimage creation.
- `--name=<sysimage1.so>`: specify path for output sysimage, defaults to jcomp-$(NOW)-sysimage.so.
- `--trace-exclude=<list>` : any lines with the supplied text will be ignored from the supplied trace file.
- `--sysimg-dir=<path>`: location for output sysimage files, defaults to $(DEFAULT_DIR).

# Flags
- `--dry-run`: only show commands, do not run anything.
- `--verbose`: verbose output.
- `--debug`: print additional debugging information 
"""
@Comonicon.main function jcomp(env=nothing;
    _trace=nothing,
    excluded=nothing,
    name="jcomp-$(NOW)-sysimage.so",
    trace_exclude=nothing,
    dir=DEFAULT_DIR,
    dry_run::Bool=false,
    verbose::Bool=false,
    debug::Bool=false,
)
    
    try
    try
        ENV["JCOMP_ENV"]

    catch
        println("Please set JCOMP_ENV")
        exit(1)
    end
    cmd_pwd = pwd()
    dry_run && println("Starting dry run, commands will be printed instead of ran")
    # local var
    trace = _trace

    if debug
        println("JCOMP_ENV: $(ENV["JCOMP_ENV"])")
        println("Pwd: $(cmd_pwd)")
        println("Args:")
        println("  j_env: $(env)")
        println("  trace: $(trace)")
        println("  excluded: $(excluded)")
        println("  name: $(name)")
        println("  trace_exclude: $(trace_exclude)")
        println("  dir: $(dir)")
        println("  verbose: $(verbose)")
        println("  dry_run: $(dry_run)")
    end

    # Check for, and make if needed sysimage directory
    try
        cd(readdir,dir)
        verbose && print("Sysimg dir $(dir) found\n")
    catch error
        # make dir if not present
        if isa(error, Base.IOError)
            verbose && print("Making directory $(dir)\n")
            try
                if !dry_run 
                    mkdir(dir)
                else
                    println("mkdir $(dir)")
                end
            catch error2
                print("Error making directory\n")
                throw(error2)
            end
        else
            # error not handled
            throw(error)
        end
    end
    
    # Init env for packages
    _env = env
    if isnothing(env) # check if env is set, otherwise use cmd_pwd
        _env = cmd_pwd
    end
    println("Activating $(_env) julia enviroment")
    verbose && println("""Pkg.activate("$(_env)")""")
    Pkg.activate(_env)
    

    # get packages
    packages = collect(ShareAdd.current_env().pkgs)
    verbose && println("Found packages: $(packages)")
    # remove excluded if present
    if !isnothing(excluded)
        filter!(p->!contains(excluded,p),packages)
        verbose && println("Packages excluded, now: $(packages)")
    end

    # Instantiate target project
    Pkg.instantiate()

    # edgecase, no packages to compile 
    if length(packages) == 0
        println("No packages to compile, exiting...")
        exit()
    end

    # return back to this enviroment
    verbose && println("Returning back to original enviroment")
    Pkg.activate(ENV["JCOMP_ENV"])

    # define sysimg creation function 
    # create sysimage without tracefile
    sysimg_cmd = """Creating sysimage file: PackageCompiler.create_sysimage($(packages);project="$(_env)",sysimage_path="$(dir)/$(name))"""
    sysimg_config = "project=\"$(_env)\",sysimage_path=\"$(dir)/$(name)\""
    function start_sysimg()
        out = "$JCOMP_TMP/jcomp-$NOW"
        out_last = "$JCOMP_TMP/jcomp-last"

        # verbose && println("Starting subprocess to create sysimg")
        script = "using Pkg;Pkg.instantiate();using PackageCompiler; println(\"Starting sysimg creation\");PackageCompiler.create_sysimage($packages; $sysimg_config)"
        cmd = """# Generated by jcomp\n$(ENV["JULIA_EXECUTABLE_PATH"]) -t auto --project=\'$(_env)\' -e '$(script)' \n"""
        verbose && println(`$(cmd)`)
        verbose && println("Sending command to $out")
        try
            cd(readdir,JCOMP_TMP)
        catch
            mkdir(JCOMP_TMP)
        end
        out = "$JCOMP_TMP/jcomp-$NOW"
        out_last = "$JCOMP_TMP/jcomp-last"
        io = open(out, "w")

        write(io,cmd)
        close(io)
       
        io = open(out_last, "w")
        write(io,cmd)
        close(io)
       
        run(`/bin/chmod +x $out`)
        run(`/bin/chmod +x $out_last`)
        println("\nTo start the compiler, run:\n$out_last")
    end

    # filter tracefile if needed, make sysimage
    if !isnothing(trace) 
        if !isnothing(trace_exclude)
            # trace present, and exclusion present 
            excluded_trace_file = tempname()
            try
                cmd = """cat $(trace) | grep --ignore-case --invert-match "$(trace_exclude)" > $(excluded_trace_file)"""
                (verbose || dry_run) && println(cmd)
                !dry_run && run(cmd)
                trace = excluded_trace_file
            catch err
                println("trace_exclude error")
                throw(err)
            end
        end

        # create sysimage with trace file
        sysimg_cmd = """Creating sysimage file: PackageCompiler.create_sysimage($(packages);project="$(_env)",sysimage_path="$(dir)/$(name)",precompile_statements_file=$(trace))"""
        sysimg_config = """$((project=_env,sysimage_path="$(dir)/$(name)",precompile_statements_file=trace)...)"""

    end
    
    # Start sysimg creation
    (verbose || dry_run) && println(sysimg_cmd)
    try
        start_sysimg()
    catch err
        println("Error making sysimage")
        throw(err )
    end

    # Verify sysimage creation
    # (verbose || dry_run) && println("Verifying sysimage creation")
    # if dry_run
    #     println("file $(dir)/$(name)")
    # else
    #     verify = run(`file $(dir)/$(name)`)
    #     if contains("cannot open",verify)
    #         println("sysimage creation failed")
    #     else
    #         println("Sysimage created at $(dir)/$(name)")
    #     end
    # end

    catch err
        if isa(err,InterruptException)
            println("\nExiting...")
            exit()
        else
            verbose && println("\n$(err)")
            exit()
        end
    end

end 
end